### ISSUE TITLE
Possible issue with roots/0

### ISSUE THREAD

**Issue by lcacciagioni** [Byzanteam-Labs/hierarch#7]
Possible unsafe operation [here](https://github.com/Byzanteam-Labs/hierarch/blob/e7e2374ef0d75d6b4426b7262cfa193d8359d501/lib/query/roots.ex#L8), when evaluating this, shouldn't be better to use something like `is_nil()` as suggested in [here](https://hexdocs.pm/ecto/Ecto.Query.html#module-nil-comparison).

**Comment by fahchen** [comment]
It's recommended to set default value `""` to ltree column, so we don't use macro `is_nil/1`
